### ISSUE TITLE
App hangs at "no search result"

### ISSUE THREAD

**Issue by joejackson3** [ArizArmeidi/FlutterWeather#8] opened 2023-07-01 18:17 UTC
Hello,
just compiled this app using my OpenWeather API key.
On first start, it says "No Search Result" after a few second. 
Return Home > spinning wheel then same result again.
How do I get started with this app?
Many thanks

**Comment by MicSoldier** [comment] 2023-11-04 13:34
Same here any suggestion ?

**Comment by ArizArmeidi** [comment] 2024-01-04 10:31
I think the issue is caused by the OpenWeather API that is used in this version is the 2.5 and the new one is 3.0. I'll look into fixing this in the upcoming release.

**Comment by ArizArmeidi** [comment] 2024-01-19 18:31
fixed with the recent release, please take a look

**Closed as completed by ArizArmeidi** 2024-01-19 18:31 UTC
